settings:
  blas95: 
    default: false
    reduce: anyTrue 
  core:
      default: true
      reduce: anyTrue 
  intel:
      default: true
      reduce: anyTrue 
  lapack95:
    default: false
    reduce: anyTrue 
  backend:
    default: sequential
    reduce: first
