sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty          
          env: VERSION=6
        - os: linux
          dist: trusty          
          env: VERSION=5
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic